### ISSUE TITLE
Doesn't load libpcap in Debian

### ISSUE THREAD

**Issue by saulshanabrook** [jsommers/switchyard#1]
When running in debian:jessie it won't load the `libpcacp` library. 

```
  File "/switchyard/srpy.py", line 14, in <module>
    from switchyard.lib.hostfirewall import Firewall
  File "/switchyard/switchyard/lib/hostfirewall.py", line 7, in <module>
    from switchyard.lib.common import log_warn, log_info, log_debug
  File "/switchyard/switchyard/lib/common.py", line 10, in <module>
    from switchyard.lib.pcapffi import pcap_devices
  File "/switchyard/switchyard/lib/pcapffi.py", line 386, in <module>
    _PcapFfi() # instantiate singleton
  File "/switchyard/switchyard/lib/pcapffi.py", line 130, in __init__
    self._libpcap = self._ffi.dlopen('libpcap.so')
  File "/usr/local/lib/python3.4/site-packages/cffi/api.py", line 118, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/local/lib/python3.4/site-packages/cffi/api.py", line 411, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/local/lib/python3.4/site-packages/cffi/api.py", line 400, in _load_backend_lib
    return backend.load_library(name, flags)
OSError: cannot load library libpcap.so: libpcap.so: cannot open shared object file: No such file or directory
```

This is because [it is looking for `libcap.so`](https://github.com/jsommers/switchyard/blob/283b506aaf0b9216a5b11515fbc616b945f2708b/switchyard/lib/pcapffi.py#L130) and in debian this library is called `libcap.so.0.8` (when installed with `apt-get install libpcap-dev`).

If I replace that line with ` self._ffi.dlopen('libpcap.so.0.8')` the library loads fine.

I am temporarily dealing with it by creating a symlink 

```
$ ln -s /usr/lib/x86_64-linux-gnu/libpcap.so.0.8 /usr/lib/x86_64-linux-gnu/libpcap.so
```

Should there be a `try...except...` there to look for multiple path libraries?

This is my first time dealing with C libraries, so maybe the problem isn't with switchyard but just with how I'm installing libpcap or linking it or something.

**Comment by saulshanabrook** [comment]
Never mind, I think the problem was that I installed `libpcap-0.8` instead of `libpcacp-dev`. Checking if that was it...

**Comment by saulshanabrook** [comment]
Yep all working great :) my bad

**Comment by jsommers** [comment]
Right.  Gotta install the dev libs for libpcap.
