### ISSUE TITLE
Support Other Python Debuggers

### ISSUE THREAD

**Issue by saulshanabrook** [jsommers/switchyard#2]
Getting thrown into pdb when a test fails is a great feature, but I wish I could instead use a different python debugger. 

For example, [ipdb](https://github.com/gotcha/ipdb) adds tab completion and a bunch of other goodies (by IPython). [wdb](https://github.com/Kozea/wdb) is pretty sweet, allowing you to debug your python code in your browser. My favorite is probably [pudb](https://pypi.python.org/pypi/pudb), which is a " full-screen, console-based visual debugger for Python."

I am not asking switchyard to provide support for any of these, but it would be really helpful if there was an easy way to swap in another debugger, maybe if there was some `Debugger` base class that anyone could subclass.

## Current Prevalence

I did a quick search of `pdb` in the code and found a few places where it crops up, and would have to be extracted out of and abstracted away.

First off there is the [switchyard/lib/debug.py](https://github.com/jsommers/switchyard/blob/6eac3f6c777e7489af8ab64aea464aa4a071ca3d/switchyard/lib/debug.py), which has this `pdb` specific line

```python
pdb.Pdb(skip=['switchyard.lib.debug']).set_trace()
```

Then there is [this monster block of code in switchyard/switch_test.py](https://github.com/jsommers/switchyard/blob/69fb48b5ab7b62a04b5bdf4901ed2df016a9ae14/switchyard/switchy_test.py#L163-L198).

```python
                    # patched-up post mortem pdb session to make sure
                    # that we start in the right place
                    p = pdb.Pdb(skip=['switchyard.lib.testing','switchyard.switchy_test'])
                    p.reset()
                    count = 0
                    xtb = tb
                    while xtb is not None:
                        count += 1
                        codestr = str(xtb.tb_frame.f_code)
                        syscode = ('switchyard/switchy_test.py' in codestr or 'switchyard/lib/testing.py' in codestr)
                        if not syscode:
                            break
                        xtb = xtb.tb_next
                    if xtb is None:
                        count -= 1
                    p.setup(None, tb)
                    for i in range(count): 
                        p.onecmd('up')
                    p.cmdloop()
```

It does a lot of hairy things with pdb, that I am pretty sure not all of the other debuggers I mentioned support (but maybe I am wrong). Would it be possible there to do something a little dummer and still retain enough functionality?

In [switchyard/monitor.py](https://github.com/jsommers/switchyard/blob/997f1286fc3e435bc56079c3ae0352df3f67bb32/switchyard/monitor.py#L143):

```python
pdb.run(debugstmt, globals={}, locals=xlocals)
```

In [switchyard/switchy_real.py](https://github.com/jsommers/switchyard/blob/6ee0f528c3704f76633df2e5bbd986bfa3a343ef/switchyard/switchy_real.py#L289-L295)

```python
            import pdb
            pdb.post_mortem()
```

**Comment by saulshanabrook** [comment]
Maybe another would just be to have an option to say "hey don't handle my exception when I am testing"

Then I could just run something like

```bash
$ python -m pudb.run switchyard/srpy.py ...
```

**Comment by jsommers** [comment]
All good suggestions.  Yeah, that one block of code which attempts to figure out the "right" stack frame to jump into would be a bit problematic, but all the other debuggers are likely using the same library that pdb uses (bdb), so it may not be quite as bad as it might seem.  

You can at least opt out of getting tossed into pdb (use the --nopdb flag), which might address your second comment?

**Comment by saulshanabrook** [comment]
I think if I opt out, it won't print any stack trace at all, but will just handle the exception and exit... I'll give it a go though.

**Comment by jsommers** [comment]
Done.  Just need to add some text in the documentation so folks know how to use this flag if they want to use some other debugger.  It's on my (private) to-do list for the docs...

**Comment by saulshanabrook** [comment]
cool :)
