### ISSUE TITLE
Access headers with dictionary-like ease from packet

### ISSUE THREAD

**Issue by saulshanabrook** [jsommers/switchyard#4]
I know index based accessing of headers from packets is possible, but had you considered allowing access by header type?

For examples, right now to get the ARP header I can do `pkt[1]` or `pkt.get_header(Arp)`. What about allowing `pkt[Arp]`?

**Comment by jsommers** [comment]
That's not unreasonable.  I'd have to think some more about the behavior it should have when the header class doesn't exist.  Right now get_header with an invalid header class returns None, but the standard behavior of indexing with a bad key is to raise a KeyError exception.  I'd probably go with the latter (and you'd get similar behavior with a bad index using the current indexing capability).

**Comment by saulshanabrook** [comment]
Yeah `KeyError` makes sense to me as well

**Comment by jsommers** [comment]
Done.  Thanks again for the suggestion.
