### ISSUE TITLE
Allow initialization of headers with values

### ISSUE THREAD

**Issue by saulshanabrook** [jsommers/switchyard#6]
Would it be possible to allow initialization of packet headers with their attributes?

Right now it is a bit cumbersome that you have to create a default header first and then set its attributes.

For example, I would love to be able to do this:

```python
import switchyard.lib.packet as packet

ip = packet.IPv4(srcip='0.0.0.1', dstip='10.1.1.4')
```

What is the rationale behind leaving out these attributes from `__init__`?

**Comment by jsommers** [comment]
I'd intended to do this, but had never made it back to implementing.  It's done now --- thanks for the suggestion!

**Comment by saulshanabrook** [comment]
Awesome! :)
