### ISSUE TITLE
Error when using kwargs for constructing ICMP header

### ISSUE THREAD

**Issue by lnyng** [jsommers/switchyard#7]
Code to generate the error
```
from switchyard.lib.packet import *
icmptype = ICMPType.DestinationUnreachable
hdr = ICMP(icmptype=icmptype, icmpcode=ICMPTypeCodeMap[icmptype].NetworkUnreachable)
```
Error message:
```
ValueError('Invalid code 0 for type 8',)
```

[Code that causes the error](https://github.com/jsommers/switchyard/blob/master/switchyard/lib/packet/packet.py#L234):
```
    def __init__(self, **kwargs):
        for attrname, value in kwargs.items():
            setattr(self, attrname, value)
```
In the code above, when iterating `kwargs` , the sequence of its values being iterated could not be ensured. In the case of error, the `icmpcode` is being set before `icmptype`, which is not valid for the default `EchoRequest` icmptype.

**Comment by jsommers** [comment]
Thanks for this report.

**Comment by jsommers** [comment]
Should be fixed now.  I also added tests to cover the issue.
